### ISSUE TITLE
How do I set this up?

### ISSUE THREAD

**Issue by ahundt** [mainanick/keras-plugins#1]
This looks super helpful! Where do I get the tokens and configure telegram, etc?

Also, would you mind making it load the tokens from a file by default like keras does with `~/.keras/keras.json` perhaps `~/.keras/kerasplugins.json`?

That would make it easy to use and hard to commit secret keys to a repository. :-)

**Comment by mainanick** [comment]
On this `~/.keras/kerasplugins.json` Were you able to set it up? if yes mind making a PR on this ?
Personally i've been using os.environ["T_SECRET"].

**Comment by ahundt** [comment]
I haven't come back to this since my previous post.

It is very easy to dump any dict to json:
https://stackoverflow.com/questions/17043860/python-dump-dict-to-json-file/26057360

It looks equally easy to load:
https://stackoverflow.com/a/48271216/99379
